name: todo_drift_app
description: "A new Flutter project"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_slidable: ^3.1.2
  drift: ^2.23.1
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.23.1
  build_runner: ^2.4.14


flutter:
  uses-material-design: true
